// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCreTgIdf2ps90ryN-dJZOimugXnT21pUU',
    appId: '1:82736473368:web:363e82f95d16937f1eaa6d',
    messagingSenderId: '82736473368',
    projectId: 'stoktakip-fc24d',
    authDomain: 'stoktakip-fc24d.firebaseapp.com',
    storageBucket: 'stoktakip-fc24d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6gZ4wDnT7KWYrHYyjGX70M0GDWyontgY',
    appId: '1:82736473368:android:249d65489a9c881e1eaa6d',
    messagingSenderId: '82736473368',
    projectId: 'stoktakip-fc24d',
    storageBucket: 'stoktakip-fc24d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvDT5Ixbw-4sfCbzRP8LoBfnkAVIudLKA',
    appId: '1:82736473368:ios:3b1b99d7122f116a1eaa6d',
    messagingSenderId: '82736473368',
    projectId: 'stoktakip-fc24d',
    storageBucket: 'stoktakip-fc24d.firebasestorage.app',
    iosBundleId: 'com.example.stokTakip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvDT5Ixbw-4sfCbzRP8LoBfnkAVIudLKA',
    appId: '1:82736473368:ios:3b1b99d7122f116a1eaa6d',
    messagingSenderId: '82736473368',
    projectId: 'stoktakip-fc24d',
    storageBucket: 'stoktakip-fc24d.firebasestorage.app',
    iosBundleId: 'com.example.stokTakip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCreTgIdf2ps90ryN-dJZOimugXnT21pUU',
    appId: '1:82736473368:web:f6ad13caff4c618d1eaa6d',
    messagingSenderId: '82736473368',
    projectId: 'stoktakip-fc24d',
    authDomain: 'stoktakip-fc24d.firebaseapp.com',
    storageBucket: 'stoktakip-fc24d.firebasestorage.app',
  );
}
